"""create executions table

Revision ID: 259e7504193a
Revises: 
Create Date: 2026-07-14 00:57:22.328843

"""
from alembic import op
import sqlalchemy as sa


revision = '259e7504193a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('github_run_id', sa.String(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_github_run_id'), 'executions', ['github_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_github_run_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
